os: linux

services:
   - docker

sudo: required
language: python

env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="test-package/0.1"
    - CONAN_USERNAME="bloodyprog"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1

  matrix:
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1

matrix:
  include:
    - os: osx
      osx_image: xcode7.1 # apple-clang 7.0
      language: generic
      env:

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
